version: '3'
services:
  backend:
    container_name: whai-back
    image: heung27/whai-back:main
    ports:
       - '80:8081' # real
#      - '8081:8081' # local
    platform: linux/amd64
    restart: always
    environment:
      - USE_PROFILE=real
    depends_on:
      - mysql
      - redis
    networks:
      - whai-net

  mysql:
    container_name: whai-mysql
    image: mysql:8.0.30
    ports:
      - '3306:3306'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=y2829!
      - MYSQL_USER=y2829
      - MYSQL_PASSWORD=Admin2829!
      - MYSQL_DATABASE=whai
    networks:
      - whai-net

  redis:
    container_name: whai-redis
    image: redis:alpine
    ports:
      - '6379:6379'
    restart: always
    networks:
      - whai-net

networks:
  whai-net:
    driver: bridge